- name: Instance state 
  hosts: localhost
  connection: local
  gather_facts: true
  

  tasks:

    - name: Stop Instance
      amazon.aws.ec2_instance_info:  
        region: eu-west-1
        aws_access_key: XXXXXXXXXXXXXXXXXX
        aws_secret_key: XXXXXXXXXXXXXXXXXX 
        filters: 
          instance-state-name: ["running"]                       # only running instances 
          vpc-id: vpc-XXXXXXXXXXXXXXXXXX
      register: result

    - name: terminate instance
      ec2: 
        region: eu-west-1
        aws_access_key: XXXXXXXXXXXXXXXXXX                        # user with sufficient permissions 
        aws_secret_key: XXXXXXXXXXXXXXXXXX
        instance_ids: "{{ result.instances[0].instance_id }}"     # check the running instances 
        state: absent                                             # shutting down and terminating the instance
