- name: VPC subnet info 
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: vpc subnet info
      ec2_vpc_subnet_info:
        region: eu-west-1                    # region, where located VPC
        aws_access_key: XXXXXXXXXXXXXXXXX    # user with sufficient permissions 
        aws_secret_key: XXXXXXXXXXXXXXXXX    
        filters: 
          vpc-id: vpc-XXXXXXXXXXXXXXXXX      # desired VPC to list subnets
      register: result                       # register variable with output
    
    - debug: msg="{{ result }}"              # debug a variable to see an output 
