- name: VPC subnet info 
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: vpc subnet info
      ec2_vpc_subnet_info:
        region: eu-west-1
        aws_access_key: XXXXXXXXXXXXXXXXX
        aws_secret_key: XXXXXXXXXXXXXXXXX 
        filters: 
          vpc-id: vpc-XXXXXXXXXXXXXXXXX
      register: result
    
    - debug: msg="{{ result }}"
